ALTER TABLE  siconv.vrpl_anexo     												OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_evento     											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_evento_frente_obra  									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_fornecedor                   							OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_frente_obra   											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_grupo_pergunta   										OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_historico_licitacao 									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_laudo     												OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_laudo_grupo_pergunta 									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_licitacao    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_lote_licitacao   										OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_macro_servico   										OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_macro_servico_parcela 									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_meta     												OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_pendencia    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_pergunta    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_po      												OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_proposta                  								OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_resposta    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_servico    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_servico_frente_obra 									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_subitem_investimento 									OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_submeta    											OWNER TO owner_siconv4_h;
ALTER TABLE  siconv.vrpl_template_laudo   										OWNER TO owner_siconv4_h;

GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_anexo_seq     	 					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_evento_seq      					TO owner_siconv4_h;
-- vrpl_evento_frente_obra - Não tem sequence (tabela de relacionamento)
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_fornecedor_seq         			TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_frente_obra_seq    				TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_grupo_pergunta_seq    				TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_historico_licitacao_seq  			TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_laudo_seq      					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_laudo_grupo_pergunta_seq  			TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_licitacao_seq     					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_lote_licitacao_seq    				TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_macro_servico_seq    				TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_macro_servico_parcela_seq  		TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_meta_seq      						TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_pendencia_seq     					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_pergunta_seq     					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_po_seq       						TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_proposta_seq          				TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_resposta_seq     					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_servico_seq     					TO owner_siconv4_h;
-- vrpl_servico_frente_obra - Não tem sequence (tabela de relacionamento)
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_subitem_investimento_seq  			TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_submeta_seq     					TO owner_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_template_laudo_seq    				TO owner_siconv4_h;

GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_anexo      			TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_evento      			TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_evento_frente_obra   TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_fornecedor     		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_frente_obra     		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_grupo_pergunta    	TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_historico_licitacao  TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_laudo      			TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_laudo_grupo_pergunta TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_licitacao     		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_lote_licitacao    	TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_macro_servico    	TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_macro_servico_parcela  TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_meta       			TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_pendencia     		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_pergunta      		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_po       			TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_proposta      		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_resposta      		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_servico      		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_servico_frente_obra  TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_subitem_investimento TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_submeta      		TO usr_siconv4_h;
GRANT SELECT, INSERT, UPDATE, DELETE  ON TABLE siconv.vrpl_template_laudo    	TO usr_siconv4_h;

ALTER FUNCTION siconv.vrpl_anexo_concorrencia_trigger()       					OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_evento_concorrencia_trigger()       					OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_evento_frente_obra_concorrencia_trigger()    		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_fornecedor_concorrencia_trigger()     				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_frente_obra_concorrencia_trigger()      				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_grupo_pergunta_concorrencia_trigger()     			OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_historico_licitacao_concorrencia_trigger()    		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_laudo_grupo_pergunta_concorrencia_trigger()    		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_laudo_concorrencia_trigger()       					OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_licitacao_concorrencia_trigger()      				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_lote_licitacao_concorrencia_trigger()     			OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_macro_servico_concorrencia_trigger()     			OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_macro_servico_parcela_concorrencia_trigger()   		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_meta_concorrencia_trigger()        					OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_pendencia_concorrencia_trigger()      				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_pergunta_concorrencia_trigger()       				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_po_concorrencia_trigger()        					OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_proposta_concorrencia_trigger()      				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_resposta_concorrencia_trigger()       				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_servico_frente_obra_concorrencia_trigger()    		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_servico_concorrencia_trigger()       				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_subitem_investimento_concorrencia_trigger()    		OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_submeta_concorrencia_trigger()       				OWNER TO owner_siconv4_h;
ALTER FUNCTION siconv.vrpl_template_laudo_concorrencia_trigger()     			OWNER TO owner_siconv4_h;
