INSERT INTO siconv.vrpl_template_laudo (tipo, versao_id, versao_nm_evento, versao_nr, versao, adt_login, adt_data_hora, adt_operacao) VALUES ('VRPL', 0, NULL, 0, 0, NULL, NULL, NULL);

INSERT INTO siconv.vrpl_grupo_pergunta (numero,          titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id,    adt_login, adt_operacao, versao,                         adt_data_hora) 
                                VALUES (     1, 'Dados do CTEF',                 true,           1,         0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (2, 'Comprovação de responsabilidade técnica e legal pelas obras/serviços', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (3, 'Regime de contratação, regime de execução e outros aspectos', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (4, 'Orçamento', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (5, 'Quadro resumo de metas de engenharia', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (6, 'Cronograma físico-financeiro', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (7, 'Relação de anexos', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (8, 'Anexos à VRPL', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (9, 'Pendências e prazo para solução', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));
INSERT INTO siconv.vrpl_grupo_pergunta (numero, titulo, in_grupo_obrigatorio, template_fk, versao_nr, versao_nm_evento, versao_id, adt_login, adt_operacao, versao,  adt_data_hora ) VALUES (10, 'Conclusão', true, 1, 0,            'INI',         1,'11111111111',    'INSERT',        0,  to_date ('17/05/2019', 'DD/MM/YYYY'));

INSERT INTO siconv.vrpl_pergunta VALUES (1, 1, 'As ARTs/RRTs de execução contemplam integralmente à Submeta?', 'LISTA', 'Sim;Não;Não apresentado;Não se aplica', '', 2, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (2, 2, 'As ARTs/RRTs de fiscalização contemplam integralmente à Submeta?', 'LISTA', 'Sim;Não;Não apresentado;Não se aplica', '', 2, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (3, 3, 'Declaração de capacidade técnica, ndicando os servidores que fiscalizarão a obra ou o serviço e informando que o Tomador possui condições físicas, operacionais, técnicas e gerenciais para a execução e fiscalização da obra ou serviço de engenharia', 'LISTA', 'Sim;Não;Não apresentado;Não se aplica', '', 2, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (4, 4, 'Comentários', 'TEXTO', '', '', 2, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (5, 1, 'Informar a opção pelo Regime de Contratação', 'LISTA', 'Lei 8.666;Lei 13.303/2016;Pregão;RDC', '', 3, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (6, 2, 'No caso de obras regidas pela Lei 8666, foi realizado pregão ou registro de preço? (Conforme o SA150 é admitido o uso do pregão para aquisição de bens e contratação de serviços comuns de engenharia, sendo vedada a utilização dessa modalidade para contratação de obras)', 'LISTA', 'Sim;Não;Não se aplica', '', 3, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (7, 3, 'Com exceção de reformas e obras lineares, foi utilizado o Regime de Execução por Empreitada Global?', 'LISTA', 'Sim;Não;Não se aplica', '', 3, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (8, 4, 'A data da licitação foi publicada após a data xx/xx/xxxx (Data emissão do LAE)?', 'LISTA', 'Sim;Não;Não se aplica', '', 3, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (9, 5, 'Comentários', 'TEXTO', '', '', 3, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (10, 1, 'Orçamento utilizado para comparação', 'LISTA', 'Aceito no LAE ou PR;Referência atualizado', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (11, 2, 'No caso de Referência atualizada, foi apresentada Declaração do Tomador informando a nova Data Base?', 'LISTA', 'Sim;Não;Não se aplica', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (12, 3, 'O preço global resultante da licitação é menor ou igual ao aceito na análise técnica ou, quando for o caso, ao valor devidamente atualizado?', 'LISTA', 'Sim;Não', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (13, 4, 'Os preços dos itens significativos / macrosserviços atendem aos critérios de aceitabilidade do AE099?', 'LISTA', 'Sim;Não', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (14, 5, 'No caso de empreitada por preço unitário, os preços dos itens de mobilização/desmobilização, canteiro/acampamento e administração local atendem aos critérios de aceitabilidade do AE099?', 'LISTA', 'Sim;Não;Não se aplica', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (15, 6, 'No caso de empreitada por preço unitário, foram verificados os quantitativos dos serviços não significativos que se tornaram significativos na licitação?', 'LISTA', 'Sim;Não;Não se aplica', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (16, 7, 'Comentários', 'TEXTO', '', '', 4, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (17, 1, 'Prazo proposto', 'READ_ONLY', 'PRAZO_PROPOSTO_CFF', '', 6, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (18, 2, 'A vigência do CTEF (ou documento de mesmo teor) é compatível com o cronograma apresentado?', 'LISTA', 'Sim;Não;Não se aplica', '', 6, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (19, 3, 'O cronograma está compatível com o orçamento apresentado?', 'LISTA', 'Sim;Não;Não se aplica', '', 6, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (20, 4, 'O cronograma cumpre as exigências do Programa (prazo máximo de construção, percentual mínimo nas últimas parcelas, etc.)?', 'LISTA', 'Sim;Não;Não se aplica', '', 6, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (21, 5, 'Comentários', 'TEXTO', '', '', 6, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (22, 1, 'Sob os aspectos técnicos, de acordo com os itens acima mencionados, consideramos o resultado do processo licitatório:', 'LISTA', 'Viável;Viável, com pendência(s);Inviável', '', 10, 0, NULL, NULL, 0, NULL, NULL, NULL);
INSERT INTO siconv.vrpl_pergunta VALUES (23, 2, 'Justificativa', 'TEXTO', '', '', 10, 0, NULL, NULL, 0, NULL, NULL, NULL);


