web: java -DDB_URL_CONNECTION_MANDATARIAS=$DB_URL_CONNECTION_MANDATARIAS -DDB_USER_MANDATARIAS=$DB_USER_MANDATARIAS -DDB_PASSWORD_MANDATARIAS=$DB_PASSWORD_MANDATARIAS -DVRPL_GRPC_PORT=$VRPL_GRPC_PORT -Xmx512m -XX:MaxMetaspaceSize=256m -XX:ParallelGCThreads=4 -XX:NewRatio=2 -XX:SurvivorRatio=20 -XX:+UseGCOverheadLimit -XX:+ExitOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -jar vrpl-grpc-server.jar


