/*
* ======================= DADOS DO SCRIPT ====================================
* AUTOR: Carlos Eugênio Palma da Purificação
* OBJETIVO: Cria a tabela CONVENIO para execução de testes
* PRE-REQUISITOS: N/A
*/
CREATE TABLE siconv.convenio (
   id bigint PRIMARY KEY NOT NULL,
   hibernate_version int DEFAULT 0 NOT NULL,
   inicio_execucao date NOT NULL,
   fim_execucao date NOT NULL,
   data_assinatura date,
   data_publicacao date,
   sequencial int NOT NULL,
   ano int NOT NULL,
   tipo_convenio int NOT NULL,
   status_convenio varchar(1024) NOT NULL,
   convenio1_fk bigint,
   convenio2_fk bigint,
   empenhado bool NOT NULL,
   publicado bool NOT NULL,
   conta_bancaria_fk bigint,
   fundamento_legal varchar(1024),
   numero_processo varchar(1024),
   numero_interno varchar(1024),
   data_versao timestamp,
   ver_seguinte_fk bigint,
   ver_antr_fk bigint,
   formalizacao_fk bigint,
   adt_operacao varchar(12) DEFAULT 'ND'::character varying NOT NULL,
   adt_data_hora timestamp DEFAULT now() NOT NULL,
   adt_login varchar(30) DEFAULT 'ND'::character varying NOT NULL,
   justificativa varchar(5000),
   permite_ajustes_cron_fisico bool DEFAULT false NOT NULL,
   historico bool,
   prorroga_gerador_hist_fk bigint,
   termo_aditivo_gerador_hist_fk bigint,
   situacao_publicacao varchar(1024),
   prazo_prestacao_contas int,
   justificativa_alteracao_adimpl varchar(5000),
   data_prestacao_contas date,
   prazo_prorrogacao_prestacao_co int,
   inadimplente bool,
   tipo_bloqueio varchar(1024) DEFAULT 'DESBLOQUEIO_TOTAL'::character varying NOT NULL,
   ordenador_despesa_fk bigint,
   gestor_financeiro_fk bigint,
   msg_erro_processamento varchar(1024),
   data_erro_processamento timestamp,
   prestacao_contas_fk bigint,
   operado_o_b_t_v bool,
   ajuste_trab_gerador_hist_fk bigint,
   justificativa_alteracao_o_b_t_ varchar(5000),
   responsavel_alteracao_o_b_t_v varchar(1024),
   data_proc_altera_opera_o_b_t_v timestamp,
   alterado_operado_o_b_t_v bool,
   efetivo bool DEFAULT true NOT NULL,
   publicacao_fk bigint,
   data_solicitacao_resgate_saldo timestamp,
   data_resgate_saldo_aplicacao timestamp,
   valor_resgatado_saldo_aplicaca numeric(15,2),
   situacao_resgate_saldo_aplicac varchar(1024),
   ugtv_sub_temp_fk bigint,
   prestacao_contas_atrasada bool,
   sol_gerador_hist_fk bigint,
   antecipacao_gerador_hist_fk bigint,
   justificativa_alteracao_dados_ varchar(1024),
   numero_controle_externo varchar(60),
   justificativa_prazo_minimo_c_n varchar(1024),
   publicacao_imprensa_fk bigint,
   rendimento_simulacao_fk bigint,
   dados_dev_saldo_obtv_fk bigint,
   apostilamento_gerador_hist_fk bigint,
   ciente_inadimplencia bool,
   situacao_inadimplencia varchar(1024),
   justificativa_inadimplencia varchar(5000)	
)
