ALTER TABLE siconv.vrpl_anexo_log_rec                    						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_evento_log_rec                    						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_evento_frente_obra_log_rec               				OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_fornecedor_log_rec                 						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_frente_obra_log_rec                 					OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_grupo_pergunta_log_rec                					OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_historico_licitacao_log_rec              				OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_laudo_grupo_pergunta_log_rec             				OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_laudo_log_rec                    						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_licitacao_log_rec                  						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_lote_licitacao_log_rec                					OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_macro_servico_log_rec			                 		OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_macro_servico_parcela_log_rec           			  	OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_meta_log_rec                			    			OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_pendencia_log_rec			                  			OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_pergunta_log_rec                   						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_po_log_rec                  			    			OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_proposta_log_rec			                			OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_resposta_log_rec                   						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_servico_frente_obra_log_rec 			             	OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_servico_log_rec 			                  			OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_subitem_investimento_log_rec             				OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_submeta_log_rec                   						OWNER TO usr_siconv4_h;
ALTER TABLE siconv.vrpl_template_laudo_log_rec                					OWNER TO usr_siconv4_h;

GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_anexo_log_rec_seq        			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_evento_log_rec_seq        			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_evento_frente_obra_log_rec_seq     TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_fornecedor_log_rec_seq       		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_frente_obra_log_rec_seq			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_grupo_pergunta_log_rec_seq      	TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_historico_licitacao_log_rec_seq    TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_laudo_grupo_pergunta_log_rec_seq   TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_laudo_log_rec_seq        			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_licitacao_log_rec_seq       		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_lote_licitacao_log_rec_seq      	TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_macro_servico_log_rec_seq      	TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_macro_servico_parcela_log_rec_seq  TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_meta_log_rec_seq         			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_pendencia_log_rec_seq       		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_pergunta_log_rec_seq        		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_po_log_rec_seq         			TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_proposta_log_rec_seq        		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_resposta_log_rec_seq        		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_servico_frente_obra_log_rec_seq    TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_servico_log_rec_seq        		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_subitem_investimento_log_rec_seq   TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_submeta_log_rec_seq        		TO usr_siconv4_h;
GRANT SELECT, USAGE  ON SEQUENCE siconv.vrpl_template_laudo_log_rec_seq      	TO usr_siconv4_h;

GRANT SELECT, INSERT  ON TABLE siconv.vrpl_anexo_log_rec          				TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_evento_log_rec						TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_evento_frente_obra_log_rec       	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_fornecedor_log_rec        			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_frente_obra_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_grupo_pergunta_log_rec        		TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_historico_licitacao_log_rec       	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_laudo_grupo_pergunta_log_rec      	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_laudo_log_rec          				TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_licitacao_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_lote_licitacao_log_rec        		TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_macro_servico_log_rec        		TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_macro_servico_parcela_log_rec      	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_meta_log_rec          				TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_pendencia_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_pergunta_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_po_log_rec           				TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_proposta_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_resposta_log_rec         			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_servico_frente_obra_log_rec       	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_servico_log_rec          			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_subitem_investimento_log_rec      	TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_submeta_log_rec          			TO usr_siconv4_h;
GRANT SELECT, INSERT  ON TABLE siconv.vrpl_template_laudo_log_rec        		TO usr_siconv4_h;
